language: ruby
sudo: false
os:
  - osx
  - linux

before_install:
  - gem install bundler
  - bundle install

script:
  - rake spec

rvm:
  - 2.2.0

bundler_args: --jobs 1 --retry 3

notifications:
  email: false